/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obchod;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Rudolf Pastva
 */
public class ObchodForm extends javax.swing.JFrame {

    private Obchod obchod;

    /**
     * Creates new form ObchodForm
     */
    public ObchodForm(Obchod obchod) {
        this.obchod = obchod;
        this.initComponents();
        datumLb.setText("Datum: " + new Date().toString());
    }

    ObchodForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        vypisPredajnuBt = new javax.swing.JButton();
        vypisSkladPredajneBt = new javax.swing.JButton();
        doplnenieTZVelkoSklBt = new javax.swing.JButton();
        vykladanieTovaruBt = new javax.swing.JButton();
        ksTf = new javax.swing.JTextField();
        idTf = new javax.swing.JTextField();
        vylVsTovarBt = new javax.swing.JButton();
        hodnotaTBt = new javax.swing.JButton();
        ponukaVSBt = new javax.swing.JButton();
        predajBt = new javax.swing.JButton();
        trzbaBt = new javax.swing.JButton();
        datumLb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setBackground(new java.awt.Color(255, 255, 255));
        desktop.setToolTipText("");
        desktop.setMinimumSize(new java.awt.Dimension(1070, 680));
        desktop.setPreferredSize(new java.awt.Dimension(1070, 680));

        vypisPredajnuBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vypisPredajnuBt.setText("Vypis predajnu");
        vypisPredajnuBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypisPredajnuBtActionPerformed(evt);
            }
        });
        desktop.add(vypisPredajnuBt);
        vypisPredajnuBt.setBounds(200, 100, 220, 40);

        vypisSkladPredajneBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vypisSkladPredajneBt.setText("Vypis Sklad predajne");
        vypisSkladPredajneBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypisSkladPredajneBtActionPerformed(evt);
            }
        });
        desktop.add(vypisSkladPredajneBt);
        vypisSkladPredajneBt.setBounds(620, 100, 220, 40);

        doplnenieTZVelkoSklBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doplnenieTZVelkoSklBt.setText("Doplnenie tovaru z velkoskladu");
        doplnenieTZVelkoSklBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doplnenieTZVelkoSklBtActionPerformed(evt);
            }
        });
        desktop.add(doplnenieTZVelkoSklBt);
        doplnenieTZVelkoSklBt.setBounds(620, 280, 220, 40);

        vykladanieTovaruBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vykladanieTovaruBt.setText("Vyloz t. zo skladu do predajne");
        vykladanieTovaruBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vykladanieTovaruBtActionPerformed(evt);
            }
        });
        desktop.add(vykladanieTovaruBt);
        vykladanieTovaruBt.setBounds(200, 460, 220, 40);

        ksTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        desktop.add(ksTf);
        ksTf.setBounds(740, 450, 100, 40);

        idTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        desktop.add(idTf);
        idTf.setBounds(740, 380, 100, 40);

        vylVsTovarBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vylVsTovarBt.setText("Vylozit vsetok tovar ");
        vylVsTovarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vylVsTovarBtActionPerformed(evt);
            }
        });
        desktop.add(vylVsTovarBt);
        vylVsTovarBt.setBounds(200, 380, 220, 40);

        hodnotaTBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hodnotaTBt.setText("Aktualna hodnota tovarov");
        hodnotaTBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hodnotaTBtActionPerformed(evt);
            }
        });
        desktop.add(hodnotaTBt);
        hodnotaTBt.setBounds(620, 190, 220, 40);

        ponukaVSBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ponukaVSBt.setText("Ponuka velkoSkladu");
        ponukaVSBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponukaVSBtActionPerformed(evt);
            }
        });
        desktop.add(ponukaVSBt);
        ponukaVSBt.setBounds(200, 280, 220, 40);

        predajBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        predajBt.setText("Predaj tovaru");
        predajBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predajBtActionPerformed(evt);
            }
        });
        desktop.add(predajBt);
        predajBt.setBounds(200, 550, 220, 40);

        trzbaBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        trzbaBt.setText("Celkova trzba");
        trzbaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trzbaBtActionPerformed(evt);
            }
        });
        desktop.add(trzbaBt);
        trzbaBt.setBounds(200, 190, 220, 40);

        datumLb.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        desktop.add(datumLb);
        datumLb.setBounds(410, 0, 310, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("id tovaru");
        desktop.add(jLabel1);
        jLabel1.setBounds(620, 390, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("pocet kusov");
        desktop.add(jLabel2);
        jLabel2.setBounds(620, 460, 80, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rudolf Pastva\\Desktop\\modre-pozadie-157922.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        desktop.add(jLabel3);
        jLabel3.setBounds(0, 0, 1110, 700);

        jMenuBar1.setToolTipText("kkk");

        jMenu1.setText("Menu");

        jMenuItem1.setText("Koniec");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Späť");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("sfddc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vypisSkladPredajneBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypisSkladPredajneBtActionPerformed
        JOptionPane.showMessageDialog(this, this.obchod.getSkladPredajne().toString());
    }//GEN-LAST:event_vypisSkladPredajneBtActionPerformed

    private void doplnenieTZVelkoSklBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doplnenieTZVelkoSklBtActionPerformed
        // TODO add your handling code here:
        try {
            this.obchod.objednajTovarZVelkoskladu(this.akciaId(), this.akciaKusy());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Chybny vstup: " + ex, null, JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_doplnenieTZVelkoSklBtActionPerformed

    private void vykladanieTovaruBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vykladanieTovaruBtActionPerformed
        // TODO add your handling code here:
        try {
            this.obchod.vylozTovarZoSkladuDoPredajne(this.akciaId(), this.akciaKusy());
            //JOptionPane.showMessageDialog(this, "Tovar vylozeny");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Chybny vstup: " + ex, null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_vykladanieTovaruBtActionPerformed

    private void vypisPredajnuBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypisPredajnuBtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, this.obchod.getPredajna().toString());
    }//GEN-LAST:event_vypisPredajnuBtActionPerformed

    private void vylVsTovarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vylVsTovarBtActionPerformed
        // TODO add your handling code here:
        try {
            this.obchod.vylozVsetokTovarZoSkladuDoPredajne(this.akciaId());
            //JOptionPane.showMessageDialog(this, "Tovar vylozeny");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Chybny vstup: " + ex, null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_vylVsTovarBtActionPerformed

    private void hodnotaTBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hodnotaTBtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, this.obchod.getPenaznyMajetok() + " eur");
    }//GEN-LAST:event_hodnotaTBtActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.akciaKoniec();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ponukaVSBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponukaVSBtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, this.obchod.getSkladPredajne().ponukaVelkoSkladu());

    }//GEN-LAST:event_ponukaVSBtActionPerformed

    private void predajBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predajBtActionPerformed
        // TODO add your handling code here:
        try {
            this.obchod.predaj(akciaId(), akciaKusy());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Chybny vstup: " + ex, null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_predajBtActionPerformed

    private void trzbaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trzbaBtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, this.obchod.getPredajna().getCelkovaTrzba());

    }//GEN-LAST:event_trzbaBtActionPerformed
    private void akciaKoniec() {
        if (JOptionPane.showConfirmDialog(this, "Chceš skutocne skončiť program", "Ukončenie", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            System.exit(1);
        }
        this.repaint();
    }

    private int akciaId() {
        int id;
        try {
            id = Integer.parseInt(this.idTf.getText());
            return id;
        } catch (NumberFormatException ex) {
            //JOptionPane.showMessageDialog(this, "Chybne id tovaru");
            throw new NumberFormatException("Chybne id tovaru");

        }

    }

    private int akciaKusy() {
        int pocetKs;
        try {
            pocetKs = Integer.parseInt(this.ksTf.getText());
        } catch (NumberFormatException ex) {
            throw new NumberFormatException("Chybny pocet kusov");
        }
        return pocetKs;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObchodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObchodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObchodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObchodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObchodForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datumLb;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton doplnenieTZVelkoSklBt;
    private javax.swing.JButton hodnotaTBt;
    private javax.swing.JTextField idTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField ksTf;
    private javax.swing.JButton ponukaVSBt;
    private javax.swing.JButton predajBt;
    private javax.swing.JButton trzbaBt;
    private javax.swing.JButton vykladanieTovaruBt;
    private javax.swing.JButton vylVsTovarBt;
    private javax.swing.JButton vypisPredajnuBt;
    private javax.swing.JButton vypisSkladPredajneBt;
    // End of variables declaration//GEN-END:variables
}
